### ISSUE TITLE
Init components repository

### ISSUE THREAD

**Issue by equinusocio** [wonderflow-bv/react-components#1]
## What

We need a local environment to build, preview and ship react-components

## How

We choose to ship the components as a single library. No mono repo managers are required (like Lerna or Bitsrc) at the moment. My proposal for the filesystem structure is the following:

```shell
/root
├── package.json
├── /vscode # required to provide project configs, snippets and so on
├── /storybook
├── /src
│   ├── /core
│   ├── /button
│   │    ├── button.module.css
│   │    ├── button.jsx # (.tsx if we use typescript)
│   │    └── index.js # (.ts if we use typescript)
```

## To do

- [ ] Project structure
- [ ] Eslint
- [ ] Stylelint
- [ ] Commitlint/Commitizen
- [ ] Postcss
- [ ] CSS Modules
- [ ] Typescript
- [ ] CI + CD
- [ ] Storybook

**Comment by alessio-libardi** [comment]
I would use `src` instead of `packages` since the `packages` folder is a convention used in monorepo projects exporting multiple libraries.
