### ISSUE TITLE
Bug: <Button> type prop collides with <button> type attribute

### ISSUE THREAD

**Issue by alessio-libardi** [wonderflow-bv/react-components#32]
Hello I have an issue using the `Button` component.

### What is happening
We can't use a submit button with secondary type since the [<Button> prop type](https://design.wonderflow.ai/develop/components/button/#usage) collids with the [<button> type attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type)

For example:
```js
<Button type="secondary" type="submit">
  Button
</Button>
```

### What I want as a user
We need to support both the change of appearance and button type at the same time.

For example:
```js
<Button apppearance="secondary" type="submit">
  Button
</Button>
```

**Comment by equinusocio** [comment]
That's good first issue. We'll allow custom button types (reset, submit, button =default) without introducing breaking changes of renaming the kind porperty to appaerance.

**Comment by alessio-libardi** [comment]
I would rename the `type` property because overriding a standard `<button>` attribute doesn't make too much sense IMO. As a Design System user having to use a different attribute and learn a new attribute when there is already a standard one that works across every browser related library isn't a good developer experience.

For the property name `appearance` was just a semantic example to let you easily understand what I meant, I'll leave it up to you to decide on the naming, just keep in mind that `type` doesn't introduce a good developer experience.

**Comment by equinusocio** [comment]
The solution is to expose a non mandatory `type` prop assigned to the `type` html attribute, which has `"button"` as default value. 

Since the `type` attribute is "mandatory" for the `<button>` element I would just expose a prop with the same name and predefined values

`kind` and `type` will then coexist to handle different things (they are not always synonyms)

**Comment by alessio-libardi** [comment]
The `htmlType` doesn't seem to be the soution we discussed together some days ago, do you mind if I ask you why you replaced `kind` with `htmlType`?

Thanks for the feedback! 🙌🏻

**Comment by equinusocio** [comment]
To avoid useless breaking changes. Anyway you are now able to set the button type.
